security:
  dataClassification: "Internal"
  dataDesignation: ["MI"]

ownership:
  driEmail: "kiran.tulsulkar@mongodb.com"
#environment secrets for staging
env:
  NODE_ENV: staging
  ENABLE_EMBEDDED_WORKERS: "true"
  ENABLE_CHANGE_STREAMS: "true"
  GL_BATCH_INTERVAL_SECONDS: "600"
  PAYMENT_LIMIT_USD: "500"
  TRANSACTIONS_BASE_URL: http://leafy-bank-bian-transactions-web-app:80
  CORE_BACKEND_URL: http://open-finance-next-gen-web-app:80
  ACCOUNTS_BACKEND_URL: http://leafy-bank-bian-accounts-web-app:80
  TRANSACTIONS_BACKEND_URL: http://leafy-bank-bian-transactions-web-app:80
  LEDGER_BACKEND_URL: http://leafy-bank-bian-ledger-web-app:80
  CHATBOT_BACKEND_URL: http://cross-be-pdf-rag-web-app:80
  OPENFINANCE_CHATBOT_BACKEND_URL: http://openfinance-chatbot-web-app:80

envSecrets:
  MONGODB_URI: leafy-bank-bian
  LEAFYBANK_DB_NAME: leafy-bank-bian

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"
