[tool.poetry]
name = "your-virtual-env"
version = "0.1.0"
description = "This repository powers the backend for Leafy Bank, managing account operations such as opening and closing accounts, and handling account cards."
authors = ["Julian Boronat <julian.boronat@mongodb.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pymongo = "^4.10.1"
python-dotenv = "^1.0.1"
fastapi = "^0.115.4"
uvicorn = "^0.32.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
