export const USER_MAP = {
    "65a546ae4a8f64e8f88fb89e": {
        UserName: "Frida",
        // Backend openfinance identity (DB UserName). The display name (UserName
        // above) diverged from the DB username, so keep the real one for API calls.
        BankUserName: "fridaklo",
        Role: "Leafy Bank Customer",
        Section: "retail",
        Employer: "Deloitte Mexico",
        EmploymentType: "FullTime",
        JobTitle: "Accountant",
        IncomeAmount: 5500,
        Currency: "USD",
        IncomeFrequency: "Monthly",
        SpendingProfile: "Spender",
    },
    "66fe219d625d93a100528224": {
        UserName: "Grace",
        BankUserName: "gracehop",
        Role: "Leafy Bank Customer",
        Section: "retail",
        Employer: "U.S. Naval Reserve",
        EmploymentType: "FullTime",
        JobTitle: "Senior Software Engineer",
        IncomeAmount: 9200,
        Currency: "USD",
        IncomeFrequency: "Monthly",
        SpendingProfile: "Saver",
    },
    "67a1000000000000000000001": {
        UserName: "Marc",
        Role: "Finance Operator",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Finance Operator",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "/gl-pipeline-monitor",
        Features: ["General Ledger Pipeline Monitor"],
    },
    "67a1000000000000000000002": {
        UserName: "Ana",
        Role: "Risk Analyst",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Risk Analyst",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://fsi-fraud-detection.industrysolutions.prod.corp.mongodb.com/?userEmail=ainhoa.mugica%40mongodb.com&sessionGoal=Development+%2F+Test",
        Features: [{ group: "ThreatSight360", items: ["Entity Management", "Entity Resolution", "Transaction Screening", "Agentic Investigation", "Risk Model Management"] }],
    },

    "67a1000000000000000000004": {
        UserName: "Sophia",
        Role: "Investment Portfolio Manager",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Investment Portfolio Manager",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://leafy-bank-ui.industrysolutions.prod.corp.mongodb.com/asset-portfolio",
        Features: ["Asset and Crypto Portfolio Management"],
    },
    "67a1000000000000000000003": {
        UserName: "Luke",
        Role: "Payments Operations",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Payments Operations",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://fsi-payments-processing.industrysolutions.prod.corp.mongodb.com/",
        Features: ["Agentic Payments System"],
    },
    "67a1000000000000000000006": {
        UserName: "Maria",
        Role: "Document Analyst",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Document Analyst",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://document-intelligence-ui.industrysolutions.prod.corp.mongodb.com/use-case",
        Features: ["Document Intelligence"],
    },
};

export const USER_LIST = Object.entries(USER_MAP).map(([id, details]) => ({
    id,
    name: details.UserName,
    // Identifier sent to the openfinance backend; falls back to the display name.
    bankUsername: details.BankUserName ?? details.UserName,
    role: details.Role,
    section: details.Section,
    employer: details.Employer,
    employmentType: details.EmploymentType,
    jobTitle: details.JobTitle,
    incomeAmount: details.IncomeAmount,
    currency: details.Currency,
    incomeFrequency: details.IncomeFrequency,
    spendingProfile: details.SpendingProfile ?? null,
    url: details.Url ?? null,
    features: details.Features ?? [],
}));